### ISSUE TITLE
CVE not parsed

### ISSUE THREAD

**Issue by toshiro92** [savon-noir/python-libnessus#10]
Hello !

I'm writing this new issue as i tried to extract the CVE from Nessus XML output (Version 2). Everything work except for the CVE, which systematicaly returns 'None', but not for another elements.

There is the code i wrote for testing purposes:

```
from libnessus.parser import NessusParser

def nessus_parser(reportfile):

      report = NessusParser.parse_fromfile(reportfile)
      for hosts in report.hosts:
          for vuln in hosts.get_report_items:

              print('CVE: {}'.format(vuln.get_vuln_risk.get('cve','None'))) #Returns None
              print('CVSS: {}'.format(vuln.get_vuln_risk.get('cvss_vector','None'))) #Worked
```

**Comment by makefu** [comment]
we found the issue, it is `vuln.get_vuln_info.get('cve',None)` instead of `get_vuln_risk`
cheers

**Comment by toshiro92** [comment]
My bad, it works now
